Develop
cmplx-xyttmt/Ride-My-Way-Andela-Bootcamp-Project pull request #2
Opened 2018-06-26 09:24 UTC by cmplx-xyttmt

Created API endpoints for rides, ride requests, create rides and create ride requests.
Feedback is appreciated.

2018-06-26 10:10 UTC, fnshemerirwe requested changes
Please add http status codes to your responses

2018-06-26 10:10 UTC, fnshemerirwe commented on .coveragerc
> +    ./venv/*
Please add a new line at the end of this file

2018-06-26 10:10 UTC, fnshemerirwe commented on .coveralls.yml
> +repo_token: PgqSvXaAwAZ7HB8YknZkNVNmjFMQcTALW
Please add a new line at the end of this file

2018-06-26 10:10 UTC, fnshemerirwe commented on .gitignore
> +app/__pycache__/
Please add a new line at the end of this file

2018-06-26 10:10 UTC, fnshemerirwe commented on .travis.yml
> +after_success: coveralls
Please add a new line at the end of this file

2018-06-26 10:10 UTC, fnshemerirwe commented on Procfile
> +web gunicorn run:app
Please add a new line at the end of this file

2018-06-26 10:10 UTC, fnshemerirwe commented on app/app.py
> +        abort(404)
Correct validations but could you please add specific error messages for each condition.

2018-06-26 10:10 UTC, fnshemerirwe commented on app/app.py
> +    if not request.is_json:
Correct validations but could you please add specific error messages for each condition.

2018-06-26 10:10 UTC, fnshemerirwe commented on app/app.py
> +    ride = rides[ride_id - 1]
What happens if my ride_id <= 0?

2018-06-26 11:12 UTC, cmplx-xyttmt commented on app/app.py
> +    ride = rides[ride_id - 1]
Oh. I'll add a condition to handle that case.

2018-06-26 12:59 UTC, cmplx-xyttmt commented on app/app.py
> +    ride = rides[ride_id - 1]
I've handled the edge case. Thanks for pointing it out.

2018-06-26 13:07 UTC, cmplx-xyttmt commented on app/app.py
> +    if not request.is_json:
Added the  new line

2018-06-26 13:07 UTC, cmplx-xyttmt commented on app/app.py
> +        abort(404)
Added the  new line

2018-06-26 13:07 UTC, cmplx-xyttmt commented on Procfile
> +web gunicorn run:app
Added the  new line

2018-06-26 13:07 UTC, cmplx-xyttmt commented on .travis.yml
> +after_success: coveralls
Added the  new line

2018-06-26 13:07 UTC, cmplx-xyttmt commented on .coveragerc
> +    ./venv/*
Added the  new line

2018-06-26 13:08 UTC, cmplx-xyttmt commented on .coveralls.yml
> +repo_token: PgqSvXaAwAZ7HB8YknZkNVNmjFMQcTALW
Added the  new line

2018-06-26 13:08 UTC, cmplx-xyttmt commented on .gitignore
> +app/__pycache__/
Added the  new line

2018-06-27 09:33 UTC, fnshemerirwe requested changes
Using `abort(400)` to handle edge cases is good, but as an end user, I can't tell what caused the bad request for example,
```if ride_id > len(rides) or ride_id <= 0:
       abort(404)```
you can return an informative error message in your responses.

2018-06-27 13:53 UTC, fnshemerirwe approved these changes

2018-06-29 08:19 UTC, merged